import { Outfit } from "next/font/google";
import "./globals.css";
import Navbar from ".././../src/components/Navbar";
import Footer from "@/components/Footer";

const OutfitFont = Outfit({
  subsets: ["latin"],
});



export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${OutfitFont.className}  h-full antialiased`}
    >
      <body className="min-h-full  flex flex-col bg-linear-to-tr from-[#473684]/20 to-[#473684]/5">

        <Navbar></Navbar>
        <main className="flex-1">
          {children}
        </main>
        <Footer></Footer>

      </body>
    </html>
  );
}
